version: '2'
services:
  dev:
    image: "python"
    build:
      context: "."
      dockerfile: python/Dockerfile
      args:
        # // Update 'VARIANT' to pick a Python version: 3, 3.9, 3.8, 3.7, 3.6.
        # // Append -bullseye or -buster to pin to an OS version.
        # // Use -bullseye variants on local on arm64/Apple Silicon.
        VARIANT: "3.9-bullseye"
        # // Node.js version: none, lts/*, 16, 14, 12, 10
        NODE_VERSION: "lts/*"
        # // Leptonica Library version: master, 1.82.0, 1.81.0, 1.80.0
        # // https://github.com/DanBloomberg/leptonica
        #LEPTONICA_TAG: "1.82.0"
        # // Tesseract OCR version: main, 5.1.0, 5.0.0, 4.1.3, 4.1.0, 4.0.0
        # // https://github.com/tesseract-ocr/tesseract
        #TESSERACT_TAG: "5.1.0"
    volumes:
      - ..:/home/vscode/ws:cached
    tty: true
